import type { Metadata } from "next";
import "./globals.css";
import { Header } from "./Components";

export const metadata: Metadata = {
  title: "Hebesha_blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="m-0 p-0  bg-white dark:bg-slate-950 scroll-container scrollbar-thin scrollbar-thumb-gray-700 scrollbar-track-gray-200">
        <Header />
        {children}
      </body>
    </html>
  );
}
